## code to prepare `dict_negate` dataset goes here
dict_negate <- dplyr::tribble(
  ~word, ~negation,
  "aint", 1,
  "arent", 1,
  "cannot", 1,
  "cant", 1,
  "couldnt", 1,
  "darent", 1,
  "didnt", 1,
  "doesnt", 1,
  "ain't", 1,
  "aren't", 1,
  "can't", 1,
  "couldn't", 1,
  "daren't", 1,
  "didn't", 1,
  "doesn't", 1,
  "dont", 1,
  "hadnt", 1,
  "hasnt", 1,
  "havent", 1,
  "isnt", 1,
  "mightnt", 1,
  "mustnt", 1,
  "neither", 1,
  "don't", 1,
  "hadn't", 1,
  "hasn't", 1,
  "haven't", 1,
  "isn't", 1,
  "mightn't", 1,
  "mustn't", 1,
  "neednt", 1,
  "needn't", 1,
  "never", 1,
  "none", 1,
  "nope", 1,
  "nor", 1,
  "not", 1,
  "nothing", 1,
  "nowhere", 1,
  "oughtnt", 1,
  "shant", 1,
  "shouldnt", 1,
  "uhuh", 1,
  "wasnt", 1,
  "werent", 1,
  "oughtn't", 1,
  "shan't", 1,
  "shouldn't", 1,
  "uh-uh", 1,
  "wasn't", 1,
  "weren't", 1,
  "without", 1,
  "wont", 1,
  "wouldnt", 1,
  "won't", 1,
  "wouldn't", 1,
  "rarely", 1,
  "seldom", 1,
  "despite", 1,
)

dict_negate <- dict_negate$word

# usethis::use_data(dict_negate, internal=TRUE, overwrite = TRUE)
