# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

strlen <- function(text) {
    .Call(`_tidyvader_strlen`, text)
}

remove_punc <- function(text) {
    .Call(`_tidyvader_remove_punc`, text)
}

remove_punc_around <- function(text) {
    .Call(`_tidyvader_remove_punc_around`, text)
}

replace_text <- function(str, pattern, replacement) {
    .Call(`_tidyvader_replace_text`, str, pattern, replacement)
}

str_split_space <- function(text) {
    .Call(`_tidyvader_str_split_space`, text)
}

cpp_str_sort <- function(strings) {
    .Call(`_tidyvader_cpp_str_sort`, strings)
}

char_count <- function(text, to_count) {
    .Call(`_tidyvader_char_count`, text, to_count)
}

vaderC <- function(word_scores, word_negations, word_boosters, word_caps, first_but) {
    .Call(`_tidyvader_vaderC`, word_scores, word_negations, word_boosters, word_caps, first_but)
}

get_index2 <- function(text, sorted_dictionary) {
    .Call(`_tidyvader_get_index2`, text, sorted_dictionary)
}

get_index3 <- function(text, sorted_dictionary) {
    .Call(`_tidyvader_get_index3`, text, sorted_dictionary)
}

vadercpp <- function(text, mod_bigrams, dict_sent_word, dict_sent_value, dict_negate, dict_mod_word, dict_mod_value, dict_punct_word, dict_punct_value) {
    .Call(`_tidyvader_vadercpp`, text, mod_bigrams, dict_sent_word, dict_sent_value, dict_negate, dict_mod_word, dict_mod_value, dict_punct_word, dict_punct_value)
}

vaderdf <- function(text_vec, mod_bigrams, dict_sent_word, dict_sent_value, dict_negate, dict_mod_word, dict_mod_value, dict_punct_word, dict_punct_value) {
    .Call(`_tidyvader_vaderdf`, text_vec, mod_bigrams, dict_sent_word, dict_sent_value, dict_negate, dict_mod_word, dict_mod_value, dict_punct_word, dict_punct_value)
}

